on:
  issues:
    types: [opened]

jobs:
  issue_creator_job:
    runs-on: ubuntu-latest
    name: Label issue and add to project
    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e
      - name: Label issue and add to project
        uses: somnolentPumpkin/issue-card-creator-and-labeler@eaff6ff1212817b2187e87bd232598e1fa1469fe
        id: hello
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          actions: '{"data": [
            {
              "label": "ecosystem",
              "project": "46",
              "repo": "ecosystem-team",
              "org": "harvesthq"
            }
          ]}'
